
dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
env:
  - SOLIDITY_COVERAGE=true

before_script:
  - npm run start &

script:
  - npm run test
