language: javascript


services:
  - rabbitmq

stages:
  - name: test
#  - name: migrate
#    if: branch = master
#  - name: release
#    if: branch = master

jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "8"
      before_install:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - npm i npm@latest -g
        - export PROXY_ADDR_PATH=$TRAVIS_BUILD_DIR/../trlProxyAddress.json
        - mkdir $TRAVIS_BUILD_DIR/../frontierjs-dev && cd $TRAVIS_BUILD_DIR/../frontierjs-dev
        - git clone https://github.com/Frontier-project/frontier-js.git
      install:
        - npm install
        - npm install -g codecov
      before_script:
        - npm install -g ganache-cli
        - npm run start &
        - npm run start:testrpc-integration &
      script:
        - truffle test
        - npm run migrate-integration
        - npm run test-integration
        - truffle migrate --reset
        #- travis_wait npm run coverage
      #after_script:
      #  - codecov
  
    # - stage: migrate
    #   if: branch = master
    #   language: node_js
    #   node_js:
    #     - "8"
    #   before_install:
    #     - npm i npm@latest -g
    #     - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    #   install:
    #     - npm install
    #   script:
    #     - truffle migrate --reset --network rinkeby_infura
    #   after_script:
    #     - npm run mock-infura

    # - stage: release
    #   provider: script
    #   node_js: "8"
    #   before_install:
    #     - npm install -g npx
    #     - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    #   script:
    #     - npx semantic-release
