language: javascript


stages:
  - Test
  - Migrate
  - Release

jobs:
  include:
    - stage: Test
      language: node_js
      node_js:
        - "8"
      before_install:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - npm i npm@latest -g
      install:
        - npm install
        - npm install -g codecov
      before_script:
        - npm install -g ganache-cli
        - npm run start &
      script:
        - truffle test
        - truffle migrate --reset
        - npm run coverage
      after_script:
        - codecov
  
    - stage: Migrate
      language: node_js
      node_js:
        - "8"
      before_install:
        - npm i npm@latest -g
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      install:
        - npm install
      script:
        - truffle migrate --reset --network rinkeby_frontier
      after_script:
        - npm run mock-infura

    - stage: Release
      provider: script
      node_js: "8"
      before_install:
        - npm install -g npx
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      script:
        - npx semantic-release
