language: node_js
node_js:
  - "8"


services:
  - rabbitmq

stages:
  - name: test
  - name: migrate
    if: type != pull_request AND (branch = master OR branch = develop)


jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "8"
      before_install:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - npm i npm@latest -g
        - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        - git submodule update --init --recursive
      install:
        - npm install -g ganache-cli
        - npm install
        - npm install -g codecov
        - export PLAYGROUND_TRLLISTENER=$TRAVIS_BUILD_DIR/../trllistener-dev
        - export PROXY_ADDR_PATH=$TRAVIS_BUILD_DIR/../trlProxyAddress.json
        - export INTEGRATION_TEST=1
        - sh ./scripts/setup-listener-integration.sh
      before_script:
        - npm run start > ganache-unittest-logs.txt & 
        - npm run start:testrpc-integration > ganache-integration-logs.txt &
      script:
        - truffle test
        - npm run migrate-integration
        - npm run test-integration
        - truffle migrate --reset
        - travis_wait npm run coverage
      after_script:
        - truffle migrate --reset --network development_integration_test
        - cd $TRAVIS_BUILD_DIR
        - truffle migrate --reset --compile-all --network development_integration_test
        - cd $PLAYGROUND_TRLLISTENER
        - npm run test-trl-int
        - export INTEGRATION_TEST=0
        - echo "Finished small-setup"
        - codecov
  
    - stage: migrate
      # if: branch = master
      language: node_js
      node_js:
        - "8"
      before_install:
        - npm i npm@latest -g
        - npm install -g npx
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      install:
        - npm install
      script:
        #- truffle migrate --reset --network rinkeby_infura
        - rm -r build
        - truffle migrate --reset --network rinkeby_frontier
        - npx semantic-release --dry-run --no-ci > semantic-release-logs.txt
        - export TRL_VERSION=$(grep "The next release version is" semantic-release-logs.txt | cut -d " " -f11)
        - cd scripts && node updateContractManager.js && cd ..
      after_script:
        - npx semantic-release
